run:
  timeout: 10m
linters:
  enable:
    - asciicheck
    - bidichk
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - forbidigo
    - gochecknoinits
    - goconst
    - gofmt
    - goheader
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nilerr
    - noctx
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - staticcheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - revive

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: atomic
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: line-length-limit
        severity: error
        arguments: [280]
      - name: unhandled-error
  govet:
    enable-all: true
    disable:
      - fieldalignment ## temporally disabled
      - shadow ## temporally disabled
  goheader:
    values:
      regexp:
        date: "20[1-2][0-9]"
    template: |-
      Copyright {{date}} The Swarm Authors. All rights reserved.
      Use of this source code is governed by a BSD-style
      license that can be found in the LICENSE file.
issues:
  exclude-rules:
    - linters:
        - goheader
      text: "go-ethereum Authors" ## disable check for other authors
    - path: _test\.go
      linters:
        - goconst ## temporally disable goconst in test
    - linters:
        - forbidigo
      path: cmd/bee/cmd
      text: "use of `fmt.Print"   ## allow fmt.Print in cmd directory
    - linters:
        - dogsled
      path: pkg/api/(.+)_test\.go # temporally disable dogsled in api test files
    - linters:
        - dogsled
      path: pkg/pushsync/(.+)_test\.go # temporally disable dogsled in pushsync test files
      # temporally disable paralleltest in following packages
    - linters:
        - paralleltest
      path: pkg/localstore
    - linters:
        - paralleltest
      path: pkg/postage
    - linters:
        - paralleltest
      path: pkg/log
    - linters:
        - paralleltest
      path: pkg/statestore
    - linters:
        - paralleltest
      path: pkg/p2p
