run:
  timeout: 10m
linters:
  enable:
    - asciicheck
    - bidichk
    - deadcode
    - depguard
    - errcheck
    - exportloopref
    - goconst
    - gofmt
    - goheader
    - gomoddirectives
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - promlinter
    - staticcheck
    - structcheck
    - thelper
    - typecheck
    - unconvert
    - unused
    - varcheck
    - wastedassign

linters-settings:
  goheader:
    values:
      regexp:
        date: "20[1-2][0-9]"
    template: |-
      Copyright {{date}} The Swarm Authors. All rights reserved.
      Use of this source code is governed by a BSD-style
      license that can be found in the LICENSE file.
issues:
  exclude-rules:
    - linters:
        - goheader
      text: "go-ethereum Authors" ## disable check for other authors
    - path: _test\.go
      linters:
        - goconst ## temporally disable goconst in test
