version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - forbidigo
    - gochecknoinits
    - goconst
    - goheader
    - goprintffuncname
    - importas
    - misspell
    - nilerr
    - noctx
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - thelper
    - unconvert
  settings:
    goheader:
      values:
        regexp:
          date: 20[1-2][0-9]
      template: |-
        Copyright {{date}} The Swarm Authors. All rights reserved.
        Use of this source code is governed by a BSD-style
        license that can be found in the LICENSE file.
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    paralleltest:
      ignore-missing: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goheader
        text: go-ethereum Authors
      - linters:
          - goconst
        path: _test\.go
      - linters:
          - forbidigo
        path: cmd/bee/cmd
        text: use of `fmt.Print
      - linters:
          - dogsled
        path: pkg/api/(.+)_test\.go
      - linters:
          - dogsled
        path: pkg/pushsync/(.+)_test\.go
      - linters:
          - paralleltest
        path: pkg/log
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
