project_name: bee

builds:
  - main: ./cmd/bee
    binary: bee
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w -X github.com/ethersphere/bee.version={{.Version}} -X github.com/ethersphere/bee.commit={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
  - id: darwin
    main: ./cmd/bee
    binary: bee
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w -X github.com/ethersphere/bee.version={{.Version}} -X github.com/ethersphere/bee.commit={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64

snapshot:
  name_template: "{{.Tag}}-snapshot"

archives:
  -
    name_template: "{{ tolower .ProjectName }}-{{ tolower .Os }}-{{ tolower .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: binary
  -
    id: homebrew
    builds:
    - darwin
    name_template: "{{ tolower .ProjectName }}-{{ tolower .Os }}-{{ tolower .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
    - packaging/homebrew/bee.yaml
    - packaging/homebrew/bee-get-addr
    - LICENSE
    - README.md

nfpms:
  - file_name_template: "{{ tolower .ProjectName }}_{{ tolower .Version }}_{{ tolower .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

    vendor: Ethereum Swarm
    homepage: https://swarm.ethereum.org/

    maintainer: Janoš Guljaš <janos@ethswarm.org>

    description: Ethereum Swarm node

    license: GPL-3

    dependencies:
      - ca-certificates
      - adduser

    formats:
      - deb
      - rpm
    
    files:
      "packaging/bee.service": "/lib/systemd/system/bee.service"
      "packaging/bee-get-addr": "/usr/bin/bee-get-addr"

    config_files:
      "packaging/bee.yaml": "/etc/bee/bee.yaml"
      "packaging/default": "/etc/default/bee"

    overrides:
      deb:
        dependencies:
          - passwd
          - ca-certificates
        scripts:
          preinstall: ./packaging/deb/preinst
          postinstall: ./packaging/deb/postinst
          preremove: ./packaging/deb/prerm
          postremove: ./packaging/deb/postrm
      rpm:
        dependencies:
          - ca-certificates
          - shadow-utils
        scripts:
          preinstall: ./packaging/rpm/pre
          postinstall: ./packaging/rpm/post
          preremove: ./packaging/rpm/preun
          postremove: ./packaging/rpm/postun

    bindir: /usr/bin

brews:
  - name: swarm-bee
    tap:
      owner: ethersphere
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_PAT }}"
    ids:
      - homebrew
    commit_author:
      name: bee-worker
      email: bee-worker@ethswarm.org
    homepage: https://swarm.ethereum.org/
    description: Ethereum Swarm node
    caveats: |
        Logs:   #{var}/log/swarm-bee/bee.log
        Config: #{etc}/swarm-bee/bee.yaml

        Bee has SWAP enabled by default and it needs ethereum endpoint to operate.
        It is recommended to use external signer with bee.
        Check documentation for more info:
        - SWAP https://docs.ethswarm.org/docs/installation/manual#swap-bandwidth-incentives
        - External signer https://docs.ethswarm.org/docs/installation/bee-clef

        After you finish configuration run 'bee-get-addr'.
    test: |
      system "#{bin}/bee version"
    install: |
      (etc/"swarm-bee").mkpath
      (var/"lib/swarm-bee").mkpath
      bin.install ["bee", "packaging/homebrew/bee-get-addr"]
      etc.install "packaging/homebrew/bee.yaml" => "swarm-bee/bee.yaml" unless File.exists? etc/"swarm-bee/bee.yaml"
    post_install: |
      system("if", "[", "!", "-f", var/"lib/swarm-bee/password", "];", "then", "openssl", "rand", "-base64", "32", "-out", var/"lib/swarm-bee/password;", "fi")
      system(bin/"bee", "init", "--config", etc/"swarm-bee/bee.yaml", ">/dev/null", "2>&1")
    plist: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>KeepAlive</key>
        <true/>
        <key>Label</key>
        <string>#{plist_name}</string>
        <key>ProgramArguments</key>
        <array>
          <string>#{bin}/bee</string>
          <string>start</string>
          <string>--config</string>
          <string>#{etc}/swarm-bee/bee.yaml</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>WorkingDirectory</key>
        <string>/usr/local</string>
        <key>StandardOutPath</key>
        <string>#{var}/log/swarm-bee/bee.log</string>
        <key>StandardErrorPath</key>
        <string>#{var}/log/swarm-bee/bee.log</string>
      </dict>
      </plist>
