openapi: 3.0.0
info:
  version: 0.4.0
  title: Common Data Types
  description: |
    \*****bzzz*****

externalDocs:
  description: Browse the documentation @ the Swarm Docs
  url: 'https://docs.swarm.eth'

paths: {}
components:
  schemas:

    Address:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/SwarmAddress'

    Addresses:
      type: object
      properties:
        overlay:
          $ref: '#/components/schemas/SwarmAddress'
        underlay:
          type: array
          items:
            $ref: '#/components/schemas/P2PUnderlay'
        ethereum:
          $ref: '#/components/schemas/EthereumAddress'
        public_key:
          $ref: '#/components/schemas/PublicKey'
        pss_public_key:
          $ref: '#/components/schemas/PublicKey'

    Balance:
      type: object
      properties:
        peer:
          $ref: '#/components/schemas/SwarmAddress'
        balance:
          type: integer

    Balances:
      type: object
      properties:
        balances:
          type: array
          items:
            $ref: '#/components/schemas/Balance'

    BzzChunksPinned:
      type: object
      properties:
        chunks:
          type: array
          items:
            type: object
            properties:
              address:
                type: string
              pinCounter:
                type: integer

    BzzTopology:
      type: object
      properties:
        baseAddr:
          $ref: '#/components/schemas/SwarmAddress'
        population:
          type: integer
        connected:
          type: integer
        timestamp:
          type: string
        nnLowWatermark:
          type: integer
        depth:
          type: integer
        bins:
          type: object
          additionalProperties:
            type: object
            properties:
              population:
                type: integer
              connected:
                type: integer
              disconnectedPeers:
                type: object
              connectedPeers:
                type: object

    Cheque:
      type: object
      properties:
        beneficiary:
          $ref: '#/components/schemas/EthereumAddress'
        chequebook:
          $ref: '#/components/schemas/EthereumAddress'
        payout:
          type: integer

    ChequeAllPeersResponse:
      type: object
      properties:
        lastcheques:
          type: array
          items:
            $ref: '#/components/schemas/ChequePeerResponse'

    ChequePeerResponse:
      type: object
      properties:
        peer:
          $ref: '#/components/schemas/SwarmAddress'
        lastreceived:
          $ref: '#/components/schemas/Cheque'
        lastsent:
          $ref: '#/components/schemas/Cheque'

    ChequebookBalance:
      type: object
      properties:
        totalBalance:
          type: integer
        availableBalance:
          type: integer

    ChequebookAddress:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/EthereumAddress'

    DateTime:
      type: string
      format: date-time
      pattern: '^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{7}\+\d{2}:\d{2})$'
      example: "2020-06-11T11:26:42.6969797+02:00"

    Duration:
      description: Go time.Duration format
      type: string
      example: "5.0018ms"

    EthereumAddress:
      type: string
      pattern: '^[A-Fa-f0-9]{40}$'
      example: "36b7efd913ca4cf880b8eeac5093fa27b0825906"

    FileName:
      type: string

    Hash:
      type: object
      properties:
        hash:
          $ref: '#/components/schemas/SwarmAddress'

    MultiAddress:
      type: string

    NewTagRequest:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/SwarmAddress'

    NewTagResponse:
      type: object
      properties:
        uid:
          $ref: '#/components/schemas/Uid'
        startedAt:
          $ref: '#/components/schemas/DateTime'
        stored:
          type: integer
        synced:
          type: integer

    NewTagDebugResponse:
      type: object
      properties:
        total:
          type: integer
        split:
          type: integer
        seen:
          type: integer
        stored:
          type: integer
        sent:
          type: integer
        synced:
          type: integer
        uid:
          $ref: '#/components/schemas/Uid'
        address:
          $ref: '#/components/schemas/SwarmAddress'
        startedAt:
          $ref: '#/components/schemas/DateTime'

    P2PUnderlay:
      type: string
      example: "/ip4/127.0.0.1/tcp/1634/p2p/16Uiu2HAmTm17toLDaPYzRyjKn27iCB76yjKnJ5DjQXneFmifFvaX"

    Peers:
      type: object
      properties:
        peers:
          type: array
          items:
            $ref: '#/components/schemas/Address'

    PinningState:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/SwarmAddress'
        pinCounter:
          type: integer

    PssRecipient:
      type: string

    PssTargets:
      type: string

    PssTopic:
      type: string

    ProblemDetails:
      type: string

    ReferenceResponse:
      type: object
      properties:
        reference:
          $ref: '#/components/schemas/SwarmReference'

    Response:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer

    RttMs:
      type: object
      properties:
        rtt:
          $ref: '#/components/schemas/Duration'

    Status:
      type: object
      properties:
        status:
          type: string

    Settlement:
      type: object
      properties:
        peer:
          $ref: "#/components/schemas/SwarmAddress"
        received:
          type: integer
        sent:
          type: integer

    Settlements:
      type: object
      properties:
        totalreceived:
          type: integer
        totalsent:
          type: integer
        settlements:
          type: array
          items:
            $ref: '#/components/schemas/Settlement'

    SwarmAddress:
      type: string
      pattern: '^[A-Fa-f0-9]{64}$'
      example: "36b7efd913ca4cf880b8eeac5093fa27b0825906c600685b6abdd6566e6cfe8f"

    PublicKey:
      type: string
      pattern: '^[A-Fa-f0-9]{66}$'
      example: "02ab7473879005929d10ce7d4f626412dad9fe56b0a6622038931d26bd79abf0a4"

    SwarmEncryptedReference:
      type: string
      pattern: '^[A-Fa-f0-9]{128}$'
      example: "36b7efd913ca4cf880b8eeac5093fa27b0825906c600685b6abdd6566e6cfe8f2d2810619d29b5dbefd5d74abce25d58b81b251baddb9c3871cf0d6967deaae2"

    DomainName:
      type: string
      pattern: '^[A-Za-z0-9]+\.[A-Za-z0-9]+$'
      example: "swarm.eth"

    SwarmReference:
      oneOf:
        - $ref: '#/components/schemas/SwarmAddress'
        - $ref: '#/components/schemas/SwarmEncryptedReference'
        - $ref: '#/components/schemas/DomainName'

    SwapCashoutResult:
      type: object
      properties:
        recipient:
          $ref: '#/components/schemas/EthereumAddress'
        lastPayout:
          type: integer
        bounced:
          type: boolean

    SwapCashoutStatus:
      type: object
      properties:
        peer:
          $ref: '#/components/schemas/SwarmAddress'
        chequebook:
          $ref: '#/components/schemas/EthereumAddress'
        cumulativePayout:
          type: integer
        beneficiary:
          $ref: '#/components/schemas/EthereumAddress'
        transactionHash:
          $ref: '#/components/schemas/TransactionHash'
        result:
          $ref: '#/components/schemas/SwapCashoutResult'

    TagName:
      type: string

    TransactionHash:
      type: string
      pattern: '^[A-Fa-f0-9]{64}$'
      example: "e28a34ffe7b1710c1baf97ca6d71d81b7f159a9920910876856c8d94dd7be4ae"

    TransactionResponse:
      type: object
      properties:
        transactionHash:
          $ref: '#/components/schemas/TransactionHash'

    Uid:
      type: integer

    WelcomeMessage:
      type: object
      properties:
        welcome_message:
          type: string

  responses:

    '204':
      description: The resource was deleted successfully.
    '400':
      description: Bad request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    '403':
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    '404':
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    '500':
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'


