openapi: 3.0.0
info:
  version: 0.1.0
  title: Bee Debug API
  description: >-
    A list of the currently provided debug interfaces to interact with the bee
    node

security:
  - {}

externalDocs:
  description: Browse the documentation @ the Swarm Docs
  url: 'https://docs.swarm.eth'

servers:
  - url: 'http://{apiRoot}:{port}'
    variables:
      apiRoot:
        default: 'localhost'
        description: Base address of the local bee node debug API
      port:
        default: 6060
        description: Service port provided in bee node config

paths:  
  '/addresses':
    get:
      summary: Get overlay and underlay addresses of the node
      tags:
        - Swarm Debug Endpoints
      responses:
        '200':
          description: Own node underlay and overlay addresses
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/Addresses'
        '500':
           $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/chunks/{address}':
    get:
      summary: Check if chunk at address exists locally
      tags:
        - Swarm Debug Endpoints
      parameters:
        - in: path
          name: address
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/SwarmAddress'
          required: true
          description: Swarm address of chunk    
      responses:
        '200':
          description: Chunk exists
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/Response'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        default:
          description: Default response
  
  '/chunks-pin/{address}':
    parameters:
        - in: path
          name: address
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/SwarmAddress'
          required: true
          description: Swarm address of chunk  
    post:
      summary: Pin chunk with given address
      tags:
        - Swarm Debug Endpoints
      responses:
        '200':
          description: Pinning chunk with address
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/Response'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        default:
          description: Default response
    delete:
      summary: Unpin chunk with given address
      tags:
        - Swarm Debug Endpoints
      responses:
        '200':
          description: Unpinning chunk with address
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/Response'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        default:
          description: Default response
    get:
      summary: Get pinning status of chunk with given address
      tags:
        - Swarm Debug Endpoints
      responses:
        '200':
          description: Pinning state of chunk  with address
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/PinningState'
        '500':
           $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response
  
  '/chunks-pin/':
    get:
      summary: Get list of pinned chunks
      tags:
        - Swarm Debug Endpoints
      responses:
        '200':
          description: List of pinned chunks
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/BzzChunksPinned'
        '500':
           $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response
  
  '/connect/{multiAddress}':
    post:
      summary: Connect to address
      tags:
        - Swarm Debug Endpoints
      parameters:
        - in: path
          allowReserved: true
          name: multiAddress
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/MultiAddress'
          required: true
          description: Underlay address of peer
      responses:
        '200':
          description: Returns overlay address of connected peer
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/Address'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/health':
    get:
      summary: Get health of node
      tags:
        - Swarm Debug Endpoints
      responses:
        '200':
          description: Health State of node
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/Status'
        default:
          description: Default response
  
  '/peers':
    get:
      summary: Get a list of peers
      tags:
        - Swarm Debug Endpoints
      responses:
        '200':
          description: Returns overlay addresses of connected peers
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/Peers'
        default:
          description: Default response

  '/peers/{address}':
    delete:
      summary: Remove peer
      tags:
        - Swarm Debug Endpoints
      parameters:
        - in: path
          name: address
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/SwarmAddress'
          required: true
          description: Swarm address of peer    
      responses:
        '200':
          description: Disconnected peer
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/Response'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response
  
  '/pingpong/{peer-id}':
    post:
      summary: Try connection to node
      tags:
        - Swarm Debug Endpoints
      parameters:
        - in: path
          name: peer-id
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/SwarmAddress'
          required: true
          description: Swarm address of peer
      responses:
        '200':
          description: Returns round trip time for given peer
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/RttMs'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response
  
  
  '/readiness':
    get:
      summary: Get readiness state of node
      tags:
        - Swarm Debug Endpoints
      responses:
        '200':
          description: Health State of node
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/Status'
        default:
          description: Default response
  
  '/tags':
    post:
      summary: 'Create Tag'
      tags: 
        - Swarm Debug Endpoints
      parameters:
        - in: query
          name: name
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/TagName'
          required: true
          description: Tagname
      responses:
        '200':
          description: New Tag Info
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/NewTagResponse'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/tags/{uid}':
    get:
      summary: 'Get Tag information using Uid'
      tags: 
        - Swarm Debug Endpoints
      parameters:
        - in: path
          name: uid
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/Uid'
          required: true
          description: Uid
      responses:
        '200':
          description: Tag info
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/NewTagResponse'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/topology':
    get:
      description: Get topology of known network
      tags:
        - Swarm Debug Endpoints
      responses:
        '200':
          description: Swarm topology of the bee node
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/BzzTopology'
    

