openapi: 3.0.0
info:
  version: 0.1.0
  title: Swarm API
  description: 'A list of the currently provided Interfaces to interact with the swarm, implementing file operations'

security:
  - {}

externalDocs:
  description: Browse the documentation @ the Swarm Docs
  url: 'https://docs.swarm.eth'

servers:

  - url: 'http://{apiRoot}:{port}/v1'
    variables:
      apiRoot:
        default: 'localhost'
        description: Base address of the local bee node main API
      port:
        default: 8080
        description: Service port provided in bee node config

  - url: 'http://{apiRoot}:{port}'
    variables:
      apiRoot:
        default: 'localhost'
        description: Base address of the local bee node main API
      port:
        default: 8080
        description: Service port provided in bee node config

paths:
  '/bytes':
    post:
      summary: 'Upload data'
      tags:
        - Bytes
      parameters:
        - in: header
          name: swarm-tag-uid
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/Uid'
          required: false
          description: Associate upload with an existing Tag UID
        - in: header
          name: swarm-pin
          schema:
            type: boolean
          required: false
          description: Represents the pinning state of the bytes
        - in: header
          name: swarm-encrypt
          schema:
            type: boolean
          required: false
          description: Represents the encrypting state of the bytes
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/ReferenceResponse'
        '403':
          $ref: 'SwarmCommon.yaml#/components/responses/403'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/bytes/{reference}':
    get:
      summary: 'Get referenced data'
      tags:
        - Bytes
      parameters:
        - in: path
          name: reference
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/SwarmReference'
          required: true
          description: Swarm address reference to content
      responses:
        '200':
          description: Retrieved content specified by reference
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/chunks/{reference}':
    get:
      summary: 'Get Chunk'
      tags:
        - Chunk
      parameters:
        - in: path
          name: reference
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/SwarmReference'
          required: true
          description: Swarm address of chunk
      responses:
        '200':
          description: Retrieved chunk content
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response
    post:
      summary: 'Upload Chunk'
      tags:
        - Chunk
      parameters:
        - in: header
          name: swarm-tag-uid
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/Uid'
          required: false
          description: Associate upload with an existing Tag UID
        - in: header
          name: swarm-pin
          schema:
            type: boolean
          required: false
          description: Represents the pinning state of the chunk
        - in: path
          name: reference
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/SwarmReference'
          required: true
          description: Swarm address of chunk
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/Status'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '403':
          $ref: 'SwarmCommon.yaml#/components/responses/403'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/files':
    post:
      summary: 'Upload file'
      tags:
        - File
      parameters:
        - in: query
          name: name
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/FileName'
          required: false
          description: Filename
        - in: header
          name: swarm-tag-uid
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/Uid'
          required: false
          description: Associate upload with an existing Tag UID
        - in: header
          name: swarm-pin
          schema:
            type: boolean
          required: false
          description: Represents the pinning state of the file
        - in: header
          name: swarm-encrypt
          schema:
            type: boolean
          required: false
          description: Represents the encrypting state of the file
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  type: array
                  items:
                    type: string
                    format: binary
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/ReferenceResponse'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '403':
          $ref: 'SwarmCommon.yaml#/components/responses/403'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/files/{reference}':
    get:
      summary: 'Get referenced file'
      tags:
        - File
      parameters:
        - in: path
          name: reference
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/SwarmReference'
          required: true
          description: Swarm address of content
      responses:
        '200':
          description: Ok
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/dirs':
    post:
      summary: 'Upload a collection'
      tags:
        - Collection
      parameters:
        - in: header
          name: swarm-tag-uid
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/Uid'
          required: false
          description: Associate upload with an existing Tag UID
        - in: header
          name: swarm-pin
          schema:
            type: boolean
          required: false
          description: Represents the pinning state of the collection
        - in: header
          name: swarm-encrypt
          schema:
            type: boolean
          required: false
          description: Represents the encrypting state of the collection
      requestBody:
        content:
          application/x-tar:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/ReferenceResponse'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '403':
          $ref: 'SwarmCommon.yaml#/components/responses/403'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/bzz/{reference}/{path}':
    get:
      summary: 'Get referenced file from a collection of files'
      tags:
        - Collection
      parameters:
        - in: path
          name: reference
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/SwarmReference'
          required: true
          description: Swarm address of content
        - in: path
          name: path
          schema:
            type: string
          required: true
          description: Path to the file in the collection.
        - in: query
          name: targets
          schema:
            type: string
          required: false
          description: Global pinning targets prefix
      responses:
        '200':
          description: Ok
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/tags':
    post:
      summary: 'Create Tag'
      tags:
        - Tag
      parameters:
        - in: query
          name: name
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/TagName'
          required: true
          description: Tagname
      responses:
        '200':
          description: New Tag Info
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/NewTagResponse'
        '403':
          $ref: 'SwarmCommon.yaml#/components/responses/403'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/tags/{uid}':
    get:
      summary: 'Get Tag information using Uid'
      tags:
        - Tag
      parameters:
        - in: path
          name: uid
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/Uid'
          required: true
          description: Uid
      responses:
        '200':
          description: Tag info
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/NewTagResponse'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '403':
          $ref: 'SwarmCommon.yaml#/components/responses/403'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response
    delete:
      summary: 'Delete Tag information using Uid'
      tags:
        - Tag
      parameters:
        - in: path
          name: uid
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/Uid'
          required: true
          description: Uid
      responses:
        '204':
          $ref: 'SwarmCommon.yaml#/components/responses/204'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '403':
          $ref: 'SwarmCommon.yaml#/components/responses/403'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response
    patch:
      summary: 'Update Total Count and swarm hash for a tag of an input stream of unknown size using Uid'
      tags:
        - Tag
      parameters:
        - in: path
          name: uid
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/Uid'
          required: true
          description: Uid
      requestBody:
        description: Can contain swarm hash to use for the tag
        required: false
        content:
          application/json:
            schema:
              $ref: 'SwarmCommon.yaml#/components/schemas/Address'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/Status'
        '403':
          $ref: 'SwarmCommon.yaml#/components/responses/403'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/pinning/chunks/{address}':
    parameters:
        - in: path
          name: address
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/SwarmAddress'
          required: true
          description: Swarm address of chunk
    post:
      summary: Pin chunk with given address
      tags:
        - Chunk pinning
      responses:
        '200':
          description: Pinning chunk with address
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/Response'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '403':
          $ref: 'SwarmCommon.yaml#/components/responses/403'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        default:
          description: Default response
    delete:
      summary: Unpin chunk with given address
      tags:
        - Chunk pinning
      responses:
        '200':
          description: Unpinning chunk with address
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/Response'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '403':
          $ref: 'SwarmCommon.yaml#/components/responses/403'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        default:
          description: Default response
    get:
      summary: Get pinning status of chunk with given address
      tags:
        - Chunk pinning
      responses:
        '200':
          description: Pinning state of chunk  with address
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/PinningState'
        '403':
          $ref: 'SwarmCommon.yaml#/components/responses/403'
        '500':
           $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/pinning/chunks':
    get:
      summary: Get list of pinned chunks
      tags:
        - Chunk pinning
      responses:
        '200':
          description: List of pinned chunks
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/BzzChunksPinned'
        '403':
          $ref: 'SwarmCommon.yaml#/components/responses/403'
        '500':
           $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response
