openapi: 3.0.0
info:
  version: 0.1.0
  title: Swarm API
  description: 'A list of the currently provided Interfaces to interact with the swarm, implementing file operations'

security:
  - {}

externalDocs:
  description: Browse the documentation @ the Swarm Docs
  url: 'https://swarm-gateways.net/bzz:/d70fb7f255b0f7ab4a0e53c186ca9803636344afde868d8d967167775a682291/'

servers:

  - url: '{apiRoot}/v1'
    variables:
        apiRoot:
          default: 'http://localhost:8080'
          description: Base address of the local bee node main API

  - url: '{apiRoot}'
    variables:
      apiRoot:
        default: 'http://localhost:8080'
        description: Base address of the local bee node main API
  
paths:
  '/bytes':
    post:
      summary: 'Upload data'
      tags: 
        - 'Endpoints on local bee node'
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/ReferenceResponse'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/bytes/{reference}':
    get:
      summary: 'Get referenced data'
      tags: 
        - 'Endpoints on local bee node'
      parameters:
        - in: path
          name: reference
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/SwarmReference'
          required: true
          description: Swarm address reference to content
      responses:
        '200':
          description: Retrieved content specified by reference
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response
          
  '/chunks/{reference}':
    get:
      summary: 'Get Chunk'
      tags: 
        - 'Endpoints on local bee node'
      parameters:
        - in: path
          name: reference
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/SwarmReference'
          required: true
          description: Swarm address of chunk   
      responses:
        '200':
          description: Retrieved chunk content
          content:
            application/octet-stream:
              schema:
                type: string  
                format: binary
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response
    post:
      summary: 'Upload Chunk'
      tags: 
        - 'Endpoints on local bee node'
      parameters:
        - in: header
          name: swarm-tag-uid
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/Uid'
          required: false
          description: Uid of chunk
        - in: header
          name: swarm-pin
          schema:
            type: boolean
          required: false
          description: Represents the pinning state of the chunk
        - in: path
          name: reference
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/SwarmReference'
          required: true
          description: Swarm address of chunk   
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/ReferenceResponse'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/files':
    post:
      summary: 'Upload file'
      tags: 
        - 'Endpoints on local bee node'
      parameters:
        - in: query
          name: name
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/FileName'
          required: false
          description: Filename
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  type: array
                  items:
                    type: string
                    format: binary
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/ReferenceResponse'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/files/{reference}':
    get:
      summary: 'Get referenced file'
      tags: 
        - 'Endpoints on local bee node'
      parameters:
        - in: path
          name: reference
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/SwarmReference'
          required: true
          description: Swarm address of content
      responses:
        '200':
          description: Ok
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
                  
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response
