# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class RttMs(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, rtt=None):  # noqa: E501
        """RttMs - a model defined in OpenAPI

        :param rtt: The rtt of this RttMs.  # noqa: E501
        :type rtt: str
        """
        self.openapi_types = {
            'rtt': str
        }

        self.attribute_map = {
            'rtt': 'rtt'
        }

        self._rtt = rtt

    @classmethod
    def from_dict(cls, dikt) -> 'RttMs':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RttMs of this RttMs.  # noqa: E501
        :rtype: RttMs
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rtt(self):
        """Gets the rtt of this RttMs.

        Go time.Duration format  # noqa: E501

        :return: The rtt of this RttMs.
        :rtype: str
        """
        return self._rtt

    @rtt.setter
    def rtt(self, rtt):
        """Sets the rtt of this RttMs.

        Go time.Duration format  # noqa: E501

        :param rtt: The rtt of this RttMs.
        :type rtt: str
        """

        self._rtt = rtt
