# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.cheque_peer_response import ChequePeerResponse
from openapi_server import util

from openapi_server.models.cheque_peer_response import ChequePeerResponse  # noqa: E501

class ChequeAllPeersResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, lastcheques=None):  # noqa: E501
        """ChequeAllPeersResponse - a model defined in OpenAPI

        :param lastcheques: The lastcheques of this ChequeAllPeersResponse.  # noqa: E501
        :type lastcheques: List[ChequePeerResponse]
        """
        self.openapi_types = {
            'lastcheques': List[ChequePeerResponse]
        }

        self.attribute_map = {
            'lastcheques': 'lastcheques'
        }

        self._lastcheques = lastcheques

    @classmethod
    def from_dict(cls, dikt) -> 'ChequeAllPeersResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChequeAllPeersResponse of this ChequeAllPeersResponse.  # noqa: E501
        :rtype: ChequeAllPeersResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lastcheques(self):
        """Gets the lastcheques of this ChequeAllPeersResponse.


        :return: The lastcheques of this ChequeAllPeersResponse.
        :rtype: List[ChequePeerResponse]
        """
        return self._lastcheques

    @lastcheques.setter
    def lastcheques(self, lastcheques):
        """Sets the lastcheques of this ChequeAllPeersResponse.


        :param lastcheques: The lastcheques of this ChequeAllPeersResponse.
        :type lastcheques: List[ChequePeerResponse]
        """

        self._lastcheques = lastcheques
