version: "3"

services:
  bee-1:
    image: ethersphere/bee:stable
    restart: unless-stopped
    environment:
      - BEE_ALLOW_PRIVATE_CIDRS
      - BEE_API_ADDR
      - BEE_AUTOTLS_CA_ENDPOINT
      - BEE_AUTOTLS_DOMAIN
      - BEE_AUTOTLS_REGISTRATION_ENDPOINT
      - BEE_BLOCK_TIME
      - BEE_BLOCK_SYNC_INTERVAL
      - BEE_BLOCKCHAIN_RPC_DIAL_TIMEOUT
      - BEE_BLOCKCHAIN_RPC_ENDPOINT
      - BEE_BLOCKCHAIN_RPC_IDLE_TIMEOUT
      - BEE_BLOCKCHAIN_RPC_KEEPALIVE
      - BEE_BLOCKCHAIN_RPC_TLS_TIMEOUT
      - BEE_BOOTNODE
      - BEE_BOOTNODE_MODE
      - BEE_CACHE_CAPACITY
      - BEE_CACHE_RETRIEVAL
      - BEE_CHEQUEBOOK_ENABLE
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_DB_BLOCK_CACHE_CAPACITY
      - BEE_DB_DISABLE_SEEKS_COMPACTION
      - BEE_DB_OPEN_FILES_LIMIT
      - BEE_DB_WRITE_BUFFER_SIZE
      - BEE_FULL_NODE
      - BEE_GAS_LIMIT_FALLBACK
      - BEE_MAINNET
      - BEE_MINIMUM_GAS_TIP_CAP
      - BEE_MINIMUM_STORAGE_RADIUS
      - BEE_NAT_ADDR
      - BEE_NAT_WSS_ADDR
      - BEE_NEIGHBORHOOD_SUGGESTER
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR
      - BEE_P2P_WS_ENABLE
      - BEE_P2P_WSS_ADDR
      - BEE_P2P_WSS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY_PERCENT
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE_PERCENT
      - BEE_POSTAGE_STAMP_ADDRESS
      - BEE_POSTAGE_STAMP_START_BLOCK
      - BEE_PPROF_MUTEX
      - BEE_PPROF_PROFILE
      - BEE_PRICE_ORACLE_ADDRESS
      - BEE_REDISTRIBUTION_ADDRESS
      - BEE_RESERVE_CAPACITY_DOUBLING
      - BEE_RESOLVER_OPTIONS
      - BEE_RESYNC
      - BEE_SKIP_POSTAGE_SNAPSHOT
      - BEE_STAKING_ADDRESS
      - BEE_STATIC_NODES
      - BEE_STATESTORE_CACHE_CAPACITY
      - BEE_STORAGE_INCENTIVES_ENABLE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_TARGET_NEIGHBORHOOD
      - BEE_TRANSACTION_DEBUG_MODE
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_HOST
      - BEE_TRACING_PORT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WARMUP_TIME
      - BEE_WELCOME_MESSAGE
      - BEE_WITHDRAWAL_ADDRESSES_WHITELIST
    ports:
      - "${API_ADDR:-1633}${BEE_API_ADDR:-:1633}"
      - "${P2P_ADDR:-1634}${BEE_P2P_ADDR:-:1634}"
      - "${P2P_WSS_ADDR:-1635}${BEE_P2P_WSS_ADDR:-:1635}"
    volumes:
      - bee-1:/home/bee/.bee
    command: start

volumes:
  bee-1:
