image:
  repository: ethersphere/bee
  tag: latest
  pullPolicy: Always

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - domain: localhost
      paths:
        - /

ingressDebug:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - domain: localhost
      paths:
        - /

serviceAccount:
  create: true

resources:
  limits:
    memory: 0.5Gi
    cpu: 0.5
  requests:
    memory: 0.25Gi
    cpu: 0.25

beeConfig:
  debug_api_enable: true
  bootnode: "/dns4/bee-0-headless.bee.svc.cluster.local/tcp/7070/p2p/16Uiu2HAm6i4dFaJt584m2jubyvnieEECgqM2YMpQ9nusXfy8XFzL"
