#!/bin/sh -e

if [ "$1" = "configure" ]; then
    if [ -z "$2" ]; then
        . /usr/share/debconf/confmodule

        db_input high bee/ethereum-endpoint || true
        if db_go; then
            db_get bee/ethereum-endpoint
            grep -v BEE_SWAP_ENDPOINT /etc/default/bee > /etc/default/bee.tmp
            echo "BEE_SWAP_ENDPOINT=$RET" >> /etc/default/bee.tmp && mv /etc/default/bee.tmp /etc/default/bee
        fi
        if [ ! -f /var/lib/bee/keys/libp2p.key ]; then
            /usr/bin/bee init --config /etc/bee/bee.yaml >/dev/null 2>&1
            chown -R bee:bee /var/lib/bee/keys
        fi
        db_input high bee/clef-enable || true
        if db_go; then
            db_get bee/clef-enable
            if [ "$RET" = true ]; then
                grep -v BEE_CLEF_SIGNER_ENABLE /etc/default/bee > /etc/default/bee.tmp
                echo "BEE_CLEF_SIGNER_ENABLE=true" >> /etc/default/bee.tmp && mv /etc/default/bee.tmp /etc/default/bee
            fi
        fi
        if [ -f /var/lib/bee/keys/swarm.key ]; then
            parse_json() { echo $1|sed -e 's/[{}]/''/g'|sed -e 's/", "/'\",\"'/g'|sed -e 's/" ,"/'\",\"'/g'|sed -e 's/" , "/'\",\"'/g'|sed -e 's/","/'\"---SEPERATOR---\"'/g'|awk -F=':' -v RS='---SEPERATOR---' "\$1~/\"$2\"/ {print}"|sed -e "s/\"$2\"://"|tr -d "\n\t"|sed -e 's/\\"/"/g'|sed -e 's/\\\\/\\/g'|sed -e 's/^[ \t]*//g'|sed -e 's/^"//' -e 's/"$//' ; }
            echo "Please make sure there is sufficient eth and bzz available on $(parse_json $(cat /var/lib/bee/keys/swarm.key) address)"
            echo "You can get both goerli eth and goerli bzz from https://faucet.ethswarm.org"
        fi
    fi

    deb-systemd-helper unmask bee.service >/dev/null || true

    if deb-systemd-helper --quiet was-enabled bee.service; then
        deb-systemd-helper enable bee.service >/dev/null || true
    else
        deb-systemd-helper update-state bee.service >/dev/null || true
    fi
    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
        deb-systemd-invoke start bee.service >/dev/null || true
    fi
fi