#!/bin/sh

set -e

BEE_USER=bee
BEE_HOME=/var/lib/bee
PWD_FILE=/var/lib/bee/password

case "$1" in
    configure)
        if ! getent passwd "$BEE_USER" > /dev/null; then
            useradd -r -d "$BEE_HOME" -s /sbin/nologin -U "$BEE_USER"
        fi
        if ! test -f "$PWD_FILE"; then
            mkdir -p "$BEE_HOME"
            < /dev/urandom tr -dc _A-Z-a-z-0-9 2> /dev/null | head -c32 > "$PWD_FILE"
            chmod 0600 "$PWD_FILE"
        fi
        ;;
esac

exit 0
