#!/bin/sh

if [ ! `id -u` -eq 0 ] ; then
    echo "
use sudo!
"
    exit 1
fi

RESP=$(/usr/bin/bee init --config /etc/bee/bee.yaml 2>&1)
case "$RESP" in
    Error*)
        echo "
Enabled clef-signer but clef is not running.
Check https://docs.ethswarm.org/ for more info.

After you fix configuration run 'sudo bee-get-addr' again.
        "
        ;;
    *)
        ETH_ADDRESS=$(echo "$RESP" | grep ethereum | cut -d' ' -f6 | tr -d '"')
        echo "
Please make sure there is sufficient eth and bzz available on $ETH_ADDRESS address.
You can get both goerli eth and goerli bzz from https://faucet.ethswarm.org?address=$ETH_ADDRESS

After you get the funds start service with 'systemctl start bee.service'.
        "
        ;;
esac
