// Copyright 2026 The Swarm Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

syntax = "proto3";

package bps;

option go_package = "pb";

message Broadcast {
  // either service or broadcast
  bytes soc = 1;
}

enum TopicBinding {
  Undefined = 0;
  Feed = 1;
}

message Join {
  bytes topic = 1;
  TopicBinding binding enum = 2; // 
  bytes principal = 3; // the "owner"
  // ============================
  bytes identity = 4; // who am i
}

enum Status {
  Undefined = 0;
  OK = 1;
  Full = 2;
  Rejected = 3;
}

message JoinAck {
  bytes challenge = 1; // the challenge to sign in order to claim the cohort's publishing role stream
  Status status enum = 2;
}

