name: Trigger ArgoCD

on:
  repository_dispatch:
    types: [trigger-beekeeper, beekeeper]
  pull_request:
    branches:
      - 'master'

jobs:
  retag:
    steps:
      - name: Wait for integration test1
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: beekeeper
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Do something with a failing build
        if: steps.wait-1.outputs.conclusion == 'failure'
        run: exit 1
      - name: Wait for integration test2
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: beekeeper_si
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Do something with a failing build
        if: steps.wait-2.conclusion == 'failure'
        run: exit 1
      - name: Wait for integration test3
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: beekeeper_clef
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Do something with a failing build
        if: steps.wait-3.conclusion == 'failure'
        run: exit 1

