name: OpenAPI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'openapi/**'
  pull_request:
    paths:
      - 'openapi/**'

jobs:
  build:
    name: Preview
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Build the OpenAPI specs
      uses: acud/openapi-dockerized@v1
      with:
        build-roots: 'openapi/Swarm.yaml'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DO_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_AWS_SECRET_ACCESS_KEY }}
        AWS_EC2_METADATA_DISABLED: true #needed when pushing to DigitalOcean Spaces
        AWS_ENDPOINT: fra1.digitaloceanspaces.com
        BUCKET_NAME: swarm-openapi-specs
