name: Workflow that triggers after-release actions

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Get the released tags version
        id: get-version
        run: |
          REF="${{ github.event.workflow_run.head_branch }}"
          echo ::set-output name=VERSION::${REF/refs\/tags\//}

      - name: Trigger Bee Factory image build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.HOMEBREW_TAP_PAT }}
          repository: ethersphere/bee-factory
          event-type: build-images
          client-payload: '{"tag": "${{ steps.get-version.outputs.VERSION }}"}'

