on: issue_comment
name: Issue Comments
jobs:
  check_comments:
    runs-on: ubuntu-latest
    name: Check comments for /test
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: test
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: write
      - name: Act on the command
        run: echo "The command was '${{ steps.command.outputs.command-name }}' with arguments '${{ steps.command.outputs.command-arguments }}'"